version: '3'
services:
  frontend:
    image: nginx:latest
    container_name: hue2m-front
    restart: always
    networks:
      - NPM
    volumes:
      - ./Frontend/build:/usr/share/nginx/html:ro

  backend:
    build: ./Backend
    container_name: hue2m-back
    restart: always
    networks:
      - NPM
      - Hue2mDB
    volumes:
      - ./Backend:/app
      - /app/node_modules
  
  mongo:
    image: mongo:latest
    container_name: hue2m-mongo
    restart: always
    networks:
      - Hue2mDB
    # ports:
    #   - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
networks:
  NPM:
    name: NPM
    external: true
  Hue2mDB:
    name: Hue2mDB
    external: false
    

