version: '3'
services:
  frontend:
    build: ./Frontend
    container_name: hue2m-front
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules

  backend:
    build: ./Backend
    container_name: hue2m-back
    ports:
      - "${BACK_PORT}:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules

