version: '3'
services:
  frontend:
    build: ./Frontend
    container_name: hue2m-front
    restart: always
    ports:
      - "${APP_PORT}:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules

  backend:
    build: ./Backend
    container_name: hue2m-back
    restart: always
    ports:
      - "${BACK_PORT}:3006"
    volumes:
      - ./Backend:/app
      - /app/node_modules
  
  mongo:
    image: mongo:latest
    container_name: hue2m-mongo
    restart: always
    # ports:
    #   - "${MONGO_PORT}:27017"
    volumes:
      - ./data:/data/db
    

